// <auto-generated />
namespace GH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class contexttypeMydataBase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(contexttypeMydataBase));
        
        string IMigrationMetadata.Id
        {
            get { return "202008280159062_context type My dataBase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
